# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.dashboard] # 'dashboard' is a branch name
  command = "export PATH='$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH' && gatsby build"
  publish = "public"
  environment = { NODE_VERSION = "10.16.3" }

